
--	Tabele do przyk³adów z projektu Loader

CREATE TABLE [dbo].[Logs](
	[LogText] [VARCHAR](255) NULL
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[SchoolTest1File](
	[SCHOOL CODE] [VARCHAR](50) NULL,
	[SCHOOL NAME] [VARCHAR](50) NULL,
	[GRADE ] [VARCHAR](50) NULL,
	[PROGRAM TYPE] [VARCHAR](50) NULL,
	[NUMBER OF STUDENTS   SEATS FILLED] [VARCHAR](50) NULL,
	[NUMBER OF SECTIONS] [VARCHAR](50) NULL,
	[AVERAGE CLASS SIZE] [VARCHAR](50) NULL,
	[SIZE OF SMALLEST CLASS] [VARCHAR](50) NULL,
	[SIZE OF LARGEST CLASS] [VARCHAR](50) NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Test1FileFixedDTs](
	[SCHOOL CODE] [VARCHAR](50) NULL,
	[SCHOOL NAME] [VARCHAR](50) NULL,
	[GRADE ] [VARCHAR](50) NULL,
	[PROGRAM TYPE] [VARCHAR](50) NULL,
	[NUMBER OF STUDENTS   SEATS FILLED] [INT] NULL,
	[NUMBER OF SECTIONS] [INT] NULL,
	[AVERAGE CLASS SIZE] [NUMERIC](18, 2) NULL,
	[SIZE OF SMALLEST CLASS] [INT] NULL,
	[SIZE OF LARGEST CLASS] [INT] NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TestManyFiles](
	[SCHOOL CODE] [VARCHAR](50) NULL,
	[SCHOOL NAME] [VARCHAR](50) NULL,
	[GRADE ] [VARCHAR](50) NULL,
	[PROGRAM TYPE] [VARCHAR](50) NULL,
	[NUMBER OF STUDENTS   SEATS FILLED] [INT] NULL,
	[NUMBER OF SECTIONS] [INT] NULL,
	[AVERAGE CLASS SIZE] [NUMERIC](18, 2) NULL,
	[SIZE OF SMALLEST CLASS] [INT] NULL,
	[SIZE OF LARGEST CLASS] [INT] NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TestManyWithAuditAndFilter](
	[SCHOOL CODE] [VARCHAR](50) NULL,
	[SCHOOL NAME] [VARCHAR](50) NULL,
	[GRADE ] [VARCHAR](50) NULL,
	[PROGRAM TYPE] [VARCHAR](50) NULL,
	[NUMBER OF STUDENTS   SEATS FILLED] [INT] NULL,
	[NUMBER OF SECTIONS] [INT] NULL,
	[AVERAGE CLASS SIZE] [NUMERIC](18, 2) NULL,
	[SIZE OF SMALLEST CLASS] [INT] NULL,
	[SIZE OF LARGEST CLASS] [INT] NULL,
	[tec_FileName] [NVARCHAR](100) NULL,
	[tec_LoadTime] [DATETIME] NULL
) ON [PRIMARY]
GO